project:
  type: website
  output-dir: docs

website:
  
  navbar:
    logo: "EL_EDUCATION_logo_white.png"
    left:
      - href: index.qmd
        text: Style Guide with <br> associated R Code

format:
  html:
    theme: 
      - simplex
      - custom.scss
    css: styles.css
    toc: true
    mainfont: Garamond
