project:
  type: website
  output-dir: docs

website:
  title: "EL Education Data Visualization Site"
  navbar:
    left:
      - href: index.qmd
        text: Style Guide with <br> associated R Code

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    mainfont: Garamond
